/**
 * Initial Supabase schema for the hosted MCP telemetry and auth layer.
 */

-- Usage telemetry. Only allow-listed parameters (symbol/ticker/timeframe) are stored.
create table if not exists mcp_usage_logs (
  id bigint generated by default as identity primary key,
  user_id text not null,
  tool_name text not null,
  parameters jsonb,
  duration_ms integer not null,
  success boolean not null,
  error_message text,
  created_at timestamp with time zone default now()
);

create index if not exists idx_mcp_usage_logs_user_id on mcp_usage_logs(user_id);
create index if not exists idx_mcp_usage_logs_created_at on mcp_usage_logs(created_at desc);

-- Cache-key rollup for edge-cache observability.
alter table mcp_usage_logs
add column if not exists cache_key text generated always as (
  lower(tool_name) || ':' ||
  coalesce((parameters->>'symbol'), (parameters->>'ticker'), 'unknown') || ':' ||
  coalesce(parameters->>'timeframe', 'unknown')
) stored;

create index if not exists idx_mcp_usage_logs_cache_key on mcp_usage_logs(cache_key);

-- API keys. Only SHA-256 hashes are stored; plaintext keys are never persisted.
create table if not exists mcp_api_keys (
  id uuid primary key default gen_random_uuid(),
  key_hash text not null unique,
  label text,
  rate_limit_per_minute integer default 60,
  allowed_tools text[] default null,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

create index if not exists idx_mcp_api_keys_key_hash on mcp_api_keys(key_hash);

-- Runtime feature flags.
create table if not exists mcp_feature_flags (
  key text primary key,
  value boolean not null,
  updated_at timestamp with time zone default now()
);

-- Seed flags.
insert into mcp_feature_flags (key, value) values
  ('disable_telemetry', false),
  ('read_only_mode', false),
  ('disable_destructive_tools', false)
on conflict (key) do nothing;
